

export const skills = [  
{ name : "HTML" ,              percent :  100 },
{ name : "CSS" ,               percent :  100 },
{ name : "SCSS" ,              percent :  100 },
{ name : "TailWind" ,          percent :  100 },
{ name : "JavaScript" ,        percent :  100 },
{ name : "Jquery" ,            percent :  100 },
{ name : "React.js" ,          percent :  100 },
{ name : "Next.js" ,           percent :  100 },
{ name : "Node.js" ,           percent :  100 },
{ name : "Express.js" ,        percent :  100 },
{ name : "MongoDB" ,           percent :  100 },
{ name : "Sqlite" ,            percent :  100 },
{ name : "MySql" ,             percent :  100 },
{ name : "SQL" ,               percent :  100 },
{ name : "PostgreSQL" ,        percent :  80  },
{ name : "Redis" ,             percent :  85  },
{ name : "PHP" ,               percent :  100 },
{ name : "Python" ,            percent :  100 },
{ name : "Django" ,            percent :  70  },
{ name : "AI" ,                percent :  60  },
{ name : "Data Science" ,      percent :  50  },
{ name : "Machine Learning" ,  percent :  50  },
{ name : "React-Native" ,      percent :  65  },
{ name : "Git" ,               percent :  90  },
{ name : "Linux / Bash" ,      percent :  80  },
{ name : "Docker" ,            percent :  100 },
{ name : "Api / Endpoints" ,   percent :  100 },
{ name : "Json" ,              percent :  100 },
{ name : "Xml" ,               percent :  70  },
{ name : "Cyber Security" ,    percent :  100 },

];